import test from 'node:test';
import assert from 'node:assert/strict';
import { parseJsonLd, parseWooHtml, shopifyHandles, parseShopifyProductJs } from '../server/adapters/html.js';
import { searchShop, PLATFORM_STRATEGIES } from '../server/adapters/index.js';
import { detectBlock, withTrace } from '../server/http.js';
import { fingerprint } from '../server/customShops.js';
import { explain, compileSeries } from '../server/classify.js';

const WOO_HTML = `
<ul class="products">
<li class="product type-product post-1 status-publish instock product_cat-one-piece">
  <a href="https://ludo.fr/produit/display-op16-fr/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
  <img src="https://ludo.fr/a.jpg"><h2 class="woocommerce-loop-product__title">Display OP16 &#8211; L&rsquo;Heure de la Bataille Décisive (FR)</h2>
  <span class="price"><del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi>149,90&nbsp;<span class="woocommerce-Price-currencySymbol">&euro;</span></bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi>129,90&nbsp;<span class="woocommerce-Price-currencySymbol">&euro;</span></bdi></span></ins></span>
  </a></li>
<li class="product type-product post-2 outofstock">
  <a href="/produit/booster-op16/" class="woocommerce-LoopProduct-link"><h2 class="woocommerce-loop-product__title">Booster OP16 FR</h2>
  <span class="price"><span class="woocommerce-Price-amount amount"><bdi>5,90&nbsp;<span class="woocommerce-Price-currencySymbol">&euro;</span></bdi></span></span></a></li>
</ul>`;

test('parseWooHtml : prix promo, stock, liens relatifs', () => {
  const [a, b] = parseWooHtml(WOO_HTML, 'https://ludo.fr/?s=OP16');
  assert.equal(a.title, 'Display OP16 – L’Heure de la Bataille Décisive (FR)');
  assert.equal(a.price, 129.9);
  assert.equal(a.available, true);
  assert.equal(b.url, 'https://ludo.fr/produit/booster-op16/');
  assert.equal(b.price, 5.9);
  assert.equal(b.available, false);
});

test('parseJsonLd : fiche produit et liste', () => {
  const html = `<script type="application/ld+json">{"@context":"https://schema.org","@graph":[{"@type":"Product","name":"Display OP-17 JP","url":"/p/op17","offers":{"@type":"Offer","price":"109.90","availability":"https://schema.org/PreOrder"}}]}</script>
  <script type="application/ld+json">{"@type":"ItemList","itemListElement":[{"@type":"ListItem","item":{"@type":"Product","name":"Booster OP-17","offers":[{"price":5.5,"availability":"OutOfStock"}]}}]}</script>`;
  const items = parseJsonLd(html, 'https://shop.fr/search');
  assert.equal(items.length, 2);
  assert.deepEqual([items[0].price, items[0].preorder, items[0].url], [109.9, true, 'https://shop.fr/p/op17']);
  assert.deepEqual([items[1].price, items[1].available], [5.5, false]);
});

test('Shopify : liens produits et fiche .js', () => {
  const html = '<a href="/products/display-op16-jp?variant=1">x</a><a href="/fr/products/booster-op16">y</a><a href="/products/display-op16-jp">z</a>';
  assert.deepEqual(shopifyHandles(html), ['display-op16-jp', 'booster-op16']);
  const p = parseShopifyProductJs({ title: 'Display OP16 JP', handle: 'display-op16-jp', price: 9990, available: true }, 'https://s.fr');
  assert.deepEqual([p.price, p.url, p.available], [99.9, 'https://s.fr/products/display-op16-jp', true]);
});

test('detectBlock : Cloudflare, Wordfence, API WordPress fermée', () => {
  const h = (o) => ({ get: (k) => o[k.toLowerCase()] ?? null });
  assert.equal(detectBlock(403, h({ server: 'cloudflare' }), '<title>Just a moment...</title>'), 'protection anti-robots Cloudflare');
  assert.equal(detectBlock(503, h({ server: 'cloudflare' }), ''), 'bloqué par Cloudflare');
  assert.equal(detectBlock(403, h({}), 'Generated by Wordfence'), 'bloqué par le pare-feu Wordfence');
  assert.equal(detectBlock(401, h({}), '{"code":"rest_not_logged_in"}'), 'API WordPress désactivée pour le public');
  assert.equal(detectBlock(503, h({ server: 'o2switch-PowerBoost-v3' }), 'Test de sécurité'), 'protection anti-robots de l’hébergeur o2switch');
  assert.equal(detectBlock(503, h({ server: 'nginx' }), 'Security check... Please turn JavaScript on and reload the page.'), 'protection anti-robots (test JavaScript)');
  assert.equal(detectBlock(503, h({ server: 'nginx' }), 'Maintenance en cours'), null);
  assert.equal(detectBlock(404, h({}), ''), null);
});

test('fingerprint de plateforme', () => {
  assert.equal(fingerprint('<script src="//cdn.shopify.com/s/files/x.js">'), 'shopify');
  assert.equal(fingerprint('<link href="/wp-content/plugins/woocommerce/a.css">'), 'woocommerce');
  assert.equal(fingerprint('<script>var prestashop = {}</script>'), 'prestashop');
  assert.equal(fingerprint('<html></html>'), null);
});

test('explain : raisons lisibles', () => {
  const [s] = compileSeries([{ id: 'OP16', queries: [], match: ['\\bOP-?16\\b'] }]);
  assert.equal(explain('OP16-118 Luffy SEC', s, 50).reason, 'carte à l’unité');
  assert.equal(explain('Display OP15 FR', s, 120).reason, 'pas la série OP16');
  assert.equal(explain('Display OP16 FR', s, null).reason, 'prix absent ou nul sur la boutique');
  assert.equal(explain('Carte One Piece Shanks OP16-020 L', s, 0).reason, 'carte à l’unité');
  assert.equal(explain('Display OP16 FR', s, 130).ok, true);
});

test('searchShop : API WooCommerce fermée (401) → repli sur la page de recherche, méthode mémorisée', async () => {
  const realFetch = globalThis.fetch;
  const calls = [];
  globalThis.fetch = async (url) => {
    calls.push(String(url));
    if (String(url).includes('/wp-json/')) return new Response('{"code":"rest_not_logged_in"}', { status: 401 });
    return new Response(WOO_HTML, { status: 200, headers: { 'content-type': 'text/html' } });
  };
  try {
    const shop = { id: 'ludo', domain: 'ludo-test.fr', base: 'https://ludo-test.fr', platform: 'woocommerce' };
    const { result, trace } = await withTrace(() => searchShop(shop, 'OP16'));
    assert.equal(result.strategy, 'wooHtml');
    assert.equal(result.items.length, 2);
    assert.equal(trace[0].status, 401);
    assert.equal(trace[0].note, 'API WordPress désactivée pour le public');
    calls.length = 0;
    await searchShop(shop, 'Bataille Décisive');
    assert.equal(calls.length, 1); // méthode qui marche essayée en premier
    assert.match(calls[0], /\?s=/);
    // Page de recherche vide (aucune méthode mémorisée) : l'API refusée (401) n'est pas réessayée.
    const shop2 = { id: 'ludo2', domain: 'ludo2-test.fr', base: 'https://ludo2-test.fr', platform: 'woocommerce' };
    globalThis.fetch = async (url) => {
      calls.push(String(url));
      if (String(url).includes('/wp-json/')) return new Response('{"code":"rest_not_logged_in"}', { status: 401 });
      return new Response('<title>Vous avez cherché OP17</title>', { status: 200, headers: { 'content-type': 'text/html' } });
    };
    calls.length = 0;
    await searchShop(shop2, 'OP17');
    await searchShop(shop2, 'OP-17');
    assert.equal(calls.filter((u) => u.includes('/wp-json/')).length, 1);
  } finally {
    globalThis.fetch = realFetch;
  }
});

test('searchShop : tout bloqué → erreur explicite', async () => {
  const realFetch = globalThis.fetch;
  globalThis.fetch = async () => new Response('<title>Just a moment...</title>', { status: 403, headers: { server: 'cloudflare' } });
  try {
    const shop = { id: 'x', domain: 'cf-test.fr', base: 'https://cf-test.fr', platform: 'prestashop' };
    await assert.rejects(searchShop(shop, 'OP16'), /Cloudflare/);
    assert.ok(PLATFORM_STRATEGIES.auto.length >= 6);
  } finally {
    globalThis.fetch = realFetch;
  }
});

test('htmlHints : titre, moteur externe, vignettes', async () => {
  const { htmlHints } = await import('../server/http.js');
  const hints = htmlHints('<title>Recherche - Philibert</title><script src="https://cdn.doofinder.com/x.js"></script>' + 'x'.repeat(4000));
  assert.ok(hints.includes('titre « Recherche - Philibert »'));
  assert.ok(hints.some((h) => /Doofinder/.test(h)));
  assert.ok(hints.includes('0 vignette(s) produit repérée(s)'));
});

test('diagnostic : contenu et serveur d’une réponse en erreur', async () => {
  const realFetch = globalThis.fetch;
  globalThis.fetch = async () => new Response('<html><body><h1>Service Unavailable</h1><p>Maintenance en cours</p></body></html>', { status: 503, headers: { server: 'nginx' } });
  try {
    const { fetchText } = await import('../server/http.js');
    const { trace } = await withTrace(() => fetchText('https://x.fr/'));
    assert.equal(trace[0].server, 'nginx');
    assert.equal(trace[0].snippet, 'Service Unavailable Maintenance en cours');
  } finally {
    globalThis.fetch = realFetch;
  }
});

test('parseProductCards : thème PrestaShop 1.6 (prix barré, lien image, rupture)', async () => {
  const { parseProductCards } = await import('../server/adapters/html.js');
  const html = `
  <ul class="product_list grid row">
   <li class="ajax_block_product col-xs-12">
    <div class="product-container" itemscope itemtype="https://schema.org/Product">
     <a class="product_img_link" href="https://www.philibertnet.com/fr/bandai/140123-one-piece-display-op17-fr-4582770058710.html" title="One Piece - Display 24 boosters OP17 - Les Guerriers les plus puissants (FR)"><img src="/img/a.jpg" alt="Display OP17"></a>
     <h5 itemprop="name"><a class="product-name" href="https://www.philibertnet.com/fr/bandai/140123-one-piece-display-op17-fr-4582770058710.html">One Piece - Display 24 boosters OP17…</a></h5>
     <div class="content_price"><span class="price product-price">139,90 €</span><span class="old-price product-price">149,90 €</span></div>
     <a class="button ajax_add_to_cart_button" href="https://www.philibertnet.com/fr/panier?add=1&id_product=140123" title="Ajouter au panier"><span>Ajouter au panier</span></a>
    </div>
   </li>
   <li class="ajax_block_product">
    <div class="product-container">
     <a class="product_img_link" href="/fr/bandai/140124-one-piece-booster-op17-fr.html"><img src="/img/b.jpg" alt="One Piece - Booster OP17 (FR)"></a>
     <span class="price product-price">5,99&nbsp;€</span><span class="availability out-of-stock">Rupture de stock</span>
    </div>
   </li>
  </ul>`;
  const [a, b] = parseProductCards(html, 'https://www.philibertnet.com/fr/recherche?s=OP17');
  assert.equal(a.title, 'One Piece - Display 24 boosters OP17 - Les Guerriers les plus puissants (FR)');
  assert.equal(a.price, 139.9);
  assert.equal(a.url, 'https://www.philibertnet.com/fr/bandai/140123-one-piece-display-op17-fr-4582770058710.html');
  assert.equal(b.title, 'One Piece - Booster OP17 (FR)');
  assert.equal(b.price, 5.99);
  assert.equal(b.available, false);
});
